config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config.merge(
    controllers: {
      sessions: 'admin_users/sessions'
    }
  )
    ActiveAdmin.routes(self)
   post '/custom_login', to: 'sessions#create', as: 'custom_login'
   get '/admin_user_mfa_session/new', to: 'admin_user_mfa_sessions#new', as: 'new_admin_user_mfa_session'
   post 'admin_user_mfa_sessions', to: 'admin_user_mfa_sessions#create', as: 'create_admin_user_mfa_sessions'
   post 'custom_post_action', to: 'admin_user_mfa_sessions#custom_post_action',as: 'custom_post_action_admin_user_mfa_sessions'
     resources :admin_users do
       get 'edit_two_factor', on: :member
       post 'check_two_factor', on: :member
     end
     mount SampleApi => '/api'
     mount CategoryApi => '/api'
     mount ProductApi => '/api'
     mount BrandsApi => '/api'
     mount RelationApi => '/api'
     mount ProductRetailerApi => '/api'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_accessor :otp_attempt # Define a virtual attribute
  attr_accessor :mfa_enabled_virtual
  attr_accessor :admin_user_id

  acts_as_google_authenticated :lookup_token => :mfa_secret, :encrypt_secrets => true
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
         def self.ransackable_attributes(auth_object = nil)
          ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
        end

end

app/models/admin_user_mfa_session.rb
class AdminUserMfaSession <  GoogleAuthenticatorRails::Session::Base
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["BrandName", "created_at", "id", "updated_at"]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["CategoryName", "created_at", "id", "updated_at"]
  end
end

app/models/product_master.rb
class ProductMaster < ApplicationRecord
  belongs_to :Category
  belongs_to :Brand

  def self.ransackable_attributes(auth_object = nil)
    ["Brand_id", "Category_id", "Description", "ProductName", "created_at", "id", "updated_at"]
  end
end

app/models/product_retailer_relation.rb
class ProductRetailerRelation < ApplicationRecord
  belongs_to :product_master
  belongs_to :retailer
  def self.ransackable_attributes(auth_object = nil)
    ["availability", "created_at", "id", "price", "product_master_id", "quantity", "retailer_id", "updated_at"]
  end
end

app/models/retailer.rb
class Retailer < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["ContactInfo", "Location", "RetailerName", "created_at", "id", "updated_at"]
  end
end

app/controllers/admin_user_mfa_sessions_controller.rb
require 'rqrcode'
require 'rotp'
class AdminUserMfaSessionsController < ApplicationController
  def custom_post_action
    email = params[:admin_user][:email]
    password = params[:admin_user][:password]
    @current_admin_user = AdminUser.find_for_database_authentication(email: email)
    if @current_admin_user && @current_admin_user.valid_password?(password)
      if redis_allow_login?(@current_admin_user)
        sign_in @current_admin_user
        if @current_admin_user.mfa_enabled
          puts "MFA Enabled"
          render :new
        else
          puts "MFA Disabled"
          redirect_to '/admin'
        end
      else
        puts "User is already logged in else where."
        redirect_to '/admin'
      end
    else
      puts "Password is Incorrect"
      redirect_to '/admin'
    end
  end
  def new
    puts "New  Function Tiggerd"
    render :new
  end
  def create
    user_id = params[:admin_user_id]
    @current_admin_user = AdminUser.find(user_id)
    user =  @current_admin_user
    if user.google_authentic?(params[:otp_attempt])
      puts"agya andar haah"
      redirect_to '/admin'
    else
      flash[:error] = "Wrong code"
      render :new
    end
  end
  private
   def redis_allow_login?(user_id)
    puts "user_id#{user_id}"
    puts "Current User Id#{current_admin_user.id}"
    redis = Redis.new
   # session_key_to_remove = 'active_sessions:2'
    #res = redis.srem('active_sessions', session_key_to_remove)
   # if res == true
    # puts "The user's session was removed."
    #puts "The user's session was not found in the set."
    #else
     # puts "An error occurred during the removal operation."
    #end
     redis_key = "active_sessions:#{current_admin_user.id}"
     if redis.sismember('active_sessions', redis_key)
     return false
     else
     redis.sadd('active_sessions', redis_key)
     redis.expire(redis_key, 3600)
     return true
     end
    end
end

app/controllers/admin_users/sessions_controller.rb
class AdminUsers::SessionsController < Devise::SessionsController
  def new
    super
  end
  def destroy
    puts "___________________________________________"
    redis = Redis.new
    session_key_to_remove = 'active_sessions:2'
    res = redis.srem('active_sessions', session_key_to_remove)
     if res == true
     puts "The user's session was removed."
     puts "The user's session was not found in the set."
     else
      puts "An error occurred during the removal operation."
     end
     new_admin_user_session_path
     super
  end
end

app/controllers/admin_users_controller.rb
require 'rqrcode'
require 'rotp'
class AdminUsersController < ApplicationController
  def destroy_admin_user_session_path
    puts"Destroy Function OverRide"
    redis = Redis.new
    redis.sismember('active_sessions', current_admin_user_id)
    sign_out current_admin_user
    redirect_to '/admin'
  end
  def edit_two_factor
    user_id = params[:id]
    @admin_user = AdminUser.find(user_id)
    if @admin_user
      sign_in @admin_user
      @admin_user.set_google_secret
      @secret_key = @admin_user.google_secret_value
      @admin_user.save
      @admin_user.reload
      @admin_user.google_qr_uri
      puts "#{@admin_user.google_qr_uri}"
      puts "#{@secret_key}"
      render :edit_two_factor
    end
  end
  def check_two_factor
    puts" Check Two Factor "
    user_id = params[:admin_user_id]
    @admin_user = AdminUser.find(user_id)
    otp_attempt = params[:admin_user][:otp_attempt]
    @admin_user.mfa_enabled = params[:admin_user][:mfa_enabled]
    @admin_user.save
    puts "OTP ATTEMPT#{otp_attempt}"
    if @admin_user.google_authentic?(otp_attempt)
      puts"agya andar haah"
      redirect_to '/admin'
    else
      puts"INvalid"
      flash[:error] = "Wrong code"
      render "admin_users/edit_two_factor"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    puts "Custom Post Action"
    @current_admin_user=resource
    if @current_admin_user
      if redis_allow_login?(@current_admin_user)
        sign_in @current_admin_user
        if@current_admin_user.mfa_enabled
          puts "MFA Enabled"
          new_admin_user_mfa_session_path
        else
          puts "MFA Disabled"
          admin_dashboard_path
        end
      else
        puts "User is already logged in elsewhere."
        new_admin_user_session_path
      end
    else
      puts "Password is Incorrect"
      new_admin_user_session_path
    end
  end
  def new
    puts "New  Function Tiggerd"
    render :new
  end
  def create
    puts "Create Function Triggered"
    user_id = params[:admin_user_id]
    current_admin_user = AdminUser.find(user_id)
    user =  current_admin_user
    if user.google_authentic?(params[:otp_attempt])
      puts"agya andar haah"
       admin_dashboard_path
    else
      flash[:error] = "Wrong code"
      new_admin_user_mfa_session_path
    end
  end
  private
   def redis_allow_login?(user_id)
    puts "Redis Allow Func"
    puts "user_id#{user_id}"
    puts "Current User Id#{current_admin_user.id}"
    redis = Redis.new

     redis_key = "active_sessions:#{current_admin_user.id}"
     if redis.sismember('active_sessions', redis_key)
     return false
     else
     redis.sadd('active_sessions', redis_key)
     redis.expire(redis_key, 3600)
     return true
     end
    end
end

app/helpers/application_helper.rb
  module ApplicationHelper
    require 'redis'
    require 'devise'

end

app/views/admin_user_mfa_sessions/new.html.erb
<p>Scan the QR code with Google Authenticator app or enter the code manually:</p>
<%= form_for :create_admin_user_mfa_sessions, url: create_admin_user_mfa_sessions_path, method: :post do |f| %>
  <%= hidden_field_tag :otp_secret %>
   <%= hidden_field_tag :admin_user_id, current_admin_user.id %>
  <%= text_field_tag :otp_attempt %>
  <%= f.submit "Submit" %>
<% end %>

app/views/admin_users/edit_two_factor.html.erb
<%= form_for @admin_user, url: check_two_factor_admin_user_path, method: :post, html: { class: "formtastic" } do |f| %>
  <fieldset class="inputs">
    <legend>
      <span>Enable/Disable 2FA</span>
    </legend>
    <ol>
      <li>
        <%= f.check_box :mfa_enabled, onchange: "if (this.checked) { enable2FA(); } else { disable2FA(); }" %>
        <%= f.label :mfa_enabled, "Enable/Disable 2FA" %>
      </li>
    </ol>
  </fieldset>
  <fieldset class="inputs" id="otp-field" style="display: none;">
    <ol>
      <li>
       <%= hidden_field_tag :otp_secret %>
       <%= hidden_field_tag :admin_user_id, @admin_user.id %>
      <img src="<%= @admin_user.google_qr_uri %>" alt="Google QR Code">
        <%= f.label :otp, "Enter OTP" %>
        <%= f.text_field :otp_attempt %>
      </li>
    </ol>
  </fieldset>

  <fieldset class="actions">
    <ol>
      <li class="action input_action">
        <%= f.submit "Save" %>
      </li>
      <li class="cancel">
        <%= link_to "Cancel", admin_admin_user_path(@admin_user.id) %>
      </li>
    </ol>
  </fieldset>
<% end %>
<script>
  function enable2FA() {
    document.getElementById('otp-field').style.display = 'block';
  }
  function disable2FA() {
    console.log("disable agya")

    document.getElementById('otp-field').style.display = 'none';
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Project4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>